/* Generated by Copilot */
#include <Token.h>

#include <chrono>
#include <functional>
#include <iomanip>
#include <random>
#include <sstream>

std::string TokenGenerator::generate() {
    // 获取当前时间戳（纳秒）
    auto now =
        std::chrono::high_resolution_clock::now().time_since_epoch().count();

    // 随机数生成器
    std::random_device rd;
    std::mt19937_64 gen(rd());
    std::uniform_int_distribution<uint64_t> dis;

    uint64_t randNum = dis(gen);

    // 拼接原始字符串
    std::string raw = std::to_string(now) + std::to_string(randNum);

    // 使用 std::hash 生成哈希值
    std::hash<std::string> hasher;
    size_t hashed = hasher(raw);

    // 转为十六进制字符串
    std::ostringstream oss;
    oss << std::hex << std::setw(16) << std::setfill('0') << hashed;
    return oss.str();
}


